name: Main CD
on:
  push:
    tags:
      - release-**
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    needs: ci
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_deps
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload build folder
          path: "./build"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
