name: Main CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
jobs:
  format_check:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_deps
      - name: Run formatting check
        run: npm run format:check
  lint_check:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_deps
      - name: Run lint check
        run: npm run lint
  type_check:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_deps
      - name: Run typecheck
        run: npm run type-check
